apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-signup-config
data:
  DJANGO_ENVIRONMENT: "{{ .Values.djangoEnvironment }}"
  DJANGO_EMAIL_HOST: "{{ .Values.djangoEmailHost }}"
  DJANGO_EMAIL_BACKEND: "{{ .Values.djangoEmailBackend }}"
  DJANGO_EMAIL_PORT: "{{ .Values.djangoEmailPort }}"
  DJANGO_DEFAULT_FROM_EMAIL: "{{ .Values.djangoEmailDefaultFrom }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-signup-secrets
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "{{ .Values.djangoSecretKey  }}"
  DJANGO_ADMIN_EMAIL: "{{ .Values.djangoAdminEmail }}"
  DJANGO_ADMIN_USERNAME: "{{ .Values.djangoAdminUsername }}"
  DJANGO_SUPERUSER_PASSWORD:  "{{ .Values.djangoAdminPassword }}"
  DJANGO_EMAIL_HOST_USER: "{{ .Values.djangoEmailUser }}"
  DJANGO_EMAIL_HOST_PASSWORD: "{{ .Values.djangoEmailPassword }}"
