# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=32)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
                ('needs', models.IntegerField()),
                ('protected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('title', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Coordinator Role Name')),
                ('source', models.TextField()),
                ('version', models.DateTimeField(auto_now_add=True, verbose_name='Changed On')),
                ('owner', models.CharField(max_length=32, verbose_name='Changed By')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('start', models.DateTimeField()),
                ('name', models.CharField(max_length=32)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='signup.Source')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Role'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Role'),
        ),
    ]
