# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('role', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Coordinator Role Name')),
                ('source', models.TextField()),
                ('version', models.DateTimeField()),
            ],
        ),
    ]
